//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp1.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj.
        /// </summary>
        public static string broj {
            get {
                return ResourceManager.GetString("broj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj golova.
        /// </summary>
        public static string brojGolova {
            get {
                return ResourceManager.GetString("brojGolova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj zutih.
        /// </summary>
        public static string brojZutih {
            get {
                return ResourceManager.GetString("brojZutih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijeli ekran.
        /// </summary>
        public static string cijeliEkran {
            get {
                return ResourceManager.GetString("cijeliEkran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izlaz.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifa kod.
        /// </summary>
        public static string fifaKod {
            get {
                return ResourceManager.GetString("fifaKod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golovi.
        /// </summary>
        public static string golovi {
            get {
                return ResourceManager.GetString("golovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GolRazlika.
        /// </summary>
        public static string golRazlika {
            get {
                return ResourceManager.GetString("golRazlika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozdrav.
        /// </summary>
        public static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string ime {
            get {
                return ResourceManager.GetString("ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        public static string jezik {
            get {
                return ResourceManager.GetString("jezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapetan.
        /// </summary>
        public static string kapetan {
            get {
                return ResourceManager.GetString("kapetan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mali ekran.
        /// </summary>
        public static string maliEkran {
            get {
                return ResourceManager.GetString("maliEkran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string naziv {
            get {
                return ResourceManager.GetString("naziv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neodlucene.
        /// </summary>
        public static string neodlucene {
            get {
                return ResourceManager.GetString("neodlucene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omiljena reprezentacija.
        /// </summary>
        public static string omiljenaReprezentacija {
            get {
                return ResourceManager.GetString("omiljenaReprezentacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobjede.
        /// </summary>
        public static string pobjede {
            get {
                return ResourceManager.GetString("pobjede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porazi.
        /// </summary>
        public static string porazi {
            get {
                return ResourceManager.GetString("porazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozicija.
        /// </summary>
        public static string pozicija {
            get {
                return ResourceManager.GetString("pozicija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikazi Statistiku.
        /// </summary>
        public static string prikaziStatistiku {
            get {
                return ResourceManager.GetString("prikaziStatistiku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primljeni golovi.
        /// </summary>
        public static string primljeniGolovi {
            get {
                return ResourceManager.GetString("primljeniGolovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistika.
        /// </summary>
        public static string statistika {
            get {
                return ResourceManager.GetString("statistika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velicina ekrana.
        /// </summary>
        public static string velicinaEkrana {
            get {
                return ResourceManager.GetString("velicinaEkrana", resourceCulture);
            }
        }
    }
}
